

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: local_proxy_manager
    restart: unless-stopped
    ports:
      # These ports are opened on the host
      - '80:80' # Public HTTP Port
      - '81:81' # Admin Web Port
      - '443:443' # Public HTTPS Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
